# Generated by Django 4.2.7 on 2024-01-27 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='genter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.PositiveIntegerField(default=0)),
                ('upi', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Prand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('mrp', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('genter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.genter')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.prand')),
            ],
        ),
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('mrp', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.product')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_by', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TotalSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30, null=True)),
                ('ph_no', models.CharField(max_length=30, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('total_amount', models.PositiveIntegerField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.payment')),
                ('product', models.ManyToManyField(to='billing.saleproduct')),
            ],
        ),
        migrations.CreateModel(
            name='stackProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('mrp', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('created_by', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.product')),
            ],
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.product_type'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.size'),
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_type_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.usertype')),
            ],
        ),
    ]
