# Generated by Django 4.2.7 on 2024-02-02 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_finalbill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalbill',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
