# Generated by Django 4.2.7 on 2024-02-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_finalbill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalbill',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
