# Generated by Django 5.0.2 on 2024-02-22 19:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_finalbill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproduct',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
